INSERT INTO currencies (code, symbol, name) VALUES
  -- Top 25 (major traded)
  ('USD', '$',   'US Dollar'),
  ('EUR', '€',   'Euro'),
  ('JPY', '¥',   'Japanese Yen'),
  ('GBP', '£',   'British Pound Sterling'),
  ('AUD', 'A$',  'Australian Dollar'),
  ('CAD', 'C$',  'Canadian Dollar'),
  ('CHF', 'Fr',  'Swiss Franc'),
  ('CNY', '¥',   'Chinese Renminbi'),
  ('HKD', 'HK$', 'Hong Kong Dollar'),
  ('NZD', 'NZ$', 'New Zealand Dollar'),
  ('SEK', 'kr',  'Swedish Krona'),
  ('KRW', '₩',   'South Korean Won'),
  ('SGD', 'S$',  'Singapore Dollar'),
  ('NOK', 'kr',  'Norwegian Krone'),
  ('MXN', 'MX$', 'Mexican Peso'),
  ('INR', '₹',   'Indian Rupee'),
  ('RUB', '₽',   'Russian Ruble'),
  ('ZAR', 'R',   'South African Rand'),
  ('TRY', '₺',   'Turkish Lira'),
  ('BRL', 'R$',  'Brazilian Real'),
  ('TWD', 'NT$', 'Taiwan Dollar'),
  ('DKK', 'kr',  'Danish Krone'),
  ('PLN', 'zł',  'Polish Złoty'),
  ('THB', '฿',   'Thai Baht'),
  ('IDR', 'Rp',  'Indonesian Rupiah'),
  -- 26-50 (emerging & regional)
  ('HUF', 'Ft',  'Hungarian Forint'),
  ('CZK', 'Kč',  'Czech Koruna'),
  ('ILS', '₪',   'Israeli New Shekel'),
  ('CLP', '$',   'Chilean Peso'),
  ('PHP', '₱',   'Philippine Peso'),
  ('AED', 'د.إ', 'UAE Dirham'),
  ('COP', '$',   'Colombian Peso'),
  ('SAR', '﷼',   'Saudi Riyal'),
  ('MYR', 'RM',  'Malaysian Ringgit'),
  ('RON', 'lei', 'Romanian Leu'),
  ('VND', '₫',   'Vietnamese Dong'),
  ('BGN', 'лв',  'Bulgarian Lev'),
  ('HRK', 'kn',  'Croatian Kuna'),
  ('PKR', '₨',   'Pakistani Rupee'),
  ('NGN', '₦',   'Nigerian Naira'),
  ('EGP', '£',   'Egyptian Pound'),
  ('BDT', '৳',   'Bangladeshi Taka'),
  ('PEN', 'S/',  'Peruvian Sol'),
  ('ARS', '$',   'Argentine Peso'),
  ('UAH', '₴',   'Ukrainian Hryvnia'),
  ('KZT', '₸',   'Kazakhstani Tenge'),
  ('QAR', '﷼',   'Qatari Riyal'),
  ('KWD', 'د.ك', 'Kuwaiti Dinar'),
  ('DZD', 'دج',  'Algerian Dinar'),
  ('IRR', '﷼',   'Iranian Rial'),
  -- 51-75 (wider global coverage)
  ('MAD', 'د.م.','Moroccan Dirham'),
  ('LKR', '₨',   'Sri Lankan Rupee'),
  ('OMR', '﷼',   'Omani Rial'),
  ('BHD', '.د.ب','Bahraini Dinar'),
  ('JOD', 'JD',  'Jordanian Dinar'),
  ('MOP', 'P',   'Macanese Pataca'),
  ('GHS', '₵',   'Ghanaian Cedi'),
  ('TND', 'د.ت', 'Tunisian Dinar'),
  ('UZS', 'сум', 'Uzbekistani Som'),
  ('ETB', 'Br',  'Ethiopian Birr'),
  ('KES', 'KSh', 'Kenyan Shilling'),
  ('MMK', 'K',   'Myanmar Kyat'),
  ('MZN', 'MT',  'Mozambican Metical'),
  ('AOA', 'Kz',  'Angolan Kwanza'),
  ('TZS', 'TSh', 'Tanzanian Shilling'),
  ('UGX', 'USh', 'Ugandan Shilling'),
  ('XAF', 'Fr',  'Central African CFA Franc'),
  ('XOF', 'Fr',  'West African CFA Franc'),
  ('RSD', 'din', 'Serbian Dinar'),
  ('HNL', 'L',   'Honduran Lempira'),
  ('GTQ', 'Q',   'Guatemalan Quetzal'),
  ('CRC', '₡',   'Costa Rican Colón'),
  ('DOP', 'RD$', 'Dominican Peso'),
  ('UYU', '$U',  'Uruguayan Peso'),
  ('AZN', '₼',   'Azerbaijani Manat'),
  -- 76-100 (broader coverage)
  ('GEL', '₾',   'Georgian Lari'),
  ('AMD', '֏',   'Armenian Dram'),
  ('BYN', 'Br',  'Belarusian Ruble'),
  ('MKD', 'ден', 'Macedonian Denar'),
  ('BAM', 'KM',  'Bosnia-Herzegovina Convertible Mark'),
  ('ALL', 'L',   'Albanian Lek'),
  ('MDL', 'L',   'Moldovan Leu'),
  ('ISK', 'kr',  'Icelandic Króna'),
  ('NPR', '₨',   'Nepalese Rupee'),
  ('KHR', '៛',   'Cambodian Riel'),
  ('LAK', '₭',   'Laotian Kip'),
  ('MNT', '₮',   'Mongolian Tögrög'),
  ('AFN', '؋',   'Afghan Afghani'),
  ('IQD', 'ع.د', 'Iraqi Dinar'),
  ('LBP', 'ل.ل', 'Lebanese Pound'),
  ('SYP', '£',   'Syrian Pound'),
  ('YER', '﷼',   'Yemeni Rial'),
  ('ZMW', 'ZK',  'Zambian Kwacha'),
  ('NAD', 'N$',  'Namibian Dollar'),
  ('BWP', 'P',   'Botswanan Pula'),
  ('MUR', '₨',   'Mauritian Rupee'),
  ('XPF', 'Fr',  'CFP Franc'),
  ('FJD', 'FJ$', 'Fijian Dollar'),
  ('PGK', 'K',   'Papua New Guinean Kina'),
  ('TTD', 'TT$', 'Trinidad and Tobago Dollar')
ON CONFLICT DO NOTHING;
